Script started on 2015年03月10日 (週二) 17時59分35秒
]0;F74016255@2015cpp: ~F74016255@2015cpp:~$ whoami: pwd
No command 'whoami:' found, did you mean:
 Command 'whoami' from package 'coreutils' (main)
whoami:: command not found
]0;F74016255@2015cpp: ~F74016255@2015cpp:~$ whoami: pwd[1P pwd; pwd
F74016255
/home/F74016255
]0;F74016255@2015cpp: ~F74016255@2015cpp:~$ git config -l
]0;F74016255@2015cpp: ~F74016255@2015cpp:~$ git clone https://github.com/MengChengHsieh/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;F74016255@2015cpp: ~F74016255@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 18時02分25秒
